### ISSUE TITLE
Remove nanoseconds from the displayed time

### ISSUE THREAD

**Issue by staraphd** [HuangYingNing/docker-logs-localtime#1]
Is it possible to remove the nanoseconds from the displayed time?

Currently it displays 
`2021-10-28 13:03:25.28039460 at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)`

I would like it to be
`2021-10-28 13:03:25 at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)`

**Comment by jathek** [comment]
> Is it possible to remove the nanoseconds from the displayed time?
> 
> Currently it displays `2021-10-28 13:03:25.28039460 at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)`
> 
> I would like it to be `2021-10-28 13:03:25 at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)`

You can edit the installed file and remove `${dateUtc:19:9}` from line 16 to do this.
